[project]
name = "hate-speech-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
    "torch>=2.7.1",
    "vllm>=0.10.1.1",
]
